"""aside-remote configuration.

Resolution order (first hit wins):
  1. real environment variables (ASIDE_REMOTE_*)
  2. env file:  ~/.aside-remote/env  then  <repo>/.env   (KEY=VALUE lines)
  3. built-in defaults (never personal)

Run `python3 scripts/setup.py` for a guided setup, or write the env file by hand —
see README for every key.
"""
from __future__ import annotations

import os
from pathlib import Path

HOME = Path.home()
BASE_DIR = Path(__file__).resolve().parent


# --- tiny env-file loader (no external deps) ---------------------------
def _load_env_files() -> None:
    for f in (HOME / ".aside-remote/env", BASE_DIR / ".env"):
        try:
            for line in f.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                k, v = k.strip(), v.strip().strip('"').strip("'")
                if k and k not in os.environ:      # real env always wins
                    os.environ[k] = v
        except OSError:
            pass


_load_env_files()
_env = os.environ.get

# --- binding -----------------------------------------------------------
HOST = _env("ASIDE_REMOTE_HOST", "127.0.0.1")
PORT = int(_env("ASIDE_REMOTE_PORT", "8799"))

# --- auth --------------------------------------------------------------
# Bearer token: the second line of defense behind whatever fronts the bridge
# (Cloudflare Access, Tailscale, a VPN...). Generated by the setup wizard.
_TOKEN_FILE = Path(_env("ASIDE_REMOTE_TOKEN_FILE", str(HOME / ".aside-remote/token"))).expanduser()
BEARER = _env("ASIDE_REMOTE_TOKEN") or (
    _TOKEN_FILE.read_text().strip() if _TOKEN_FILE.exists() else ""
)
if not BEARER:
    # Fail closed: an empty token would let every request through.
    # Auto-provision one instead — same thing the wizard does.
    import secrets as _secrets
    BEARER = _secrets.token_urlsafe(32)
    _TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    _TOKEN_FILE.write_text(BEARER + "\n")
    _TOKEN_FILE.chmod(0o600)

# --- Aside paths -------------------------------------------------------
# 사용자 테마 CSS — 있으면 기본 스타일 뒤에 로드된다 (README "테마" 참고)
THEME_CSS = Path(_env("ASIDE_REMOTE_THEME_CSS", str(HOME / ".aside-remote/theme.css"))).expanduser()

ASIDE_BIN = str(Path(_env("ASIDE_BIN", str(HOME / ".local/bin/aside"))).expanduser())
# CLI account id. Must match the user dir below (u0 -> ~/.aside/u/0) — a different
# account makes the bridge look in the wrong place for sessions. Every CLI call
# passes it explicitly; set it empty to leave the choice to the CLI.
ASIDE_ACCOUNT = _env("ASIDE_ACCOUNT", "u0")
ASIDE_USER_DIR = Path(_env("ASIDE_USER_DIR",
                           str(HOME / ".aside/u" / (ASIDE_ACCOUNT.lstrip("u") or "0")))).expanduser()
SESSIONS_DIR = ASIDE_USER_DIR / "sessions"
# Attachments live here. The repl sandbox rejects paths outside
# "Project and session roots", but the Aside user root is allowed (measured).
# Anything under the bridge's own cache dir would be unreadable to the agent.
UPLOAD_DIR = ASIDE_USER_DIR / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
UPLOAD_MAX_BYTES = int(_env("ASIDE_REMOTE_UPLOAD_MAX", str(24 * 1024 * 1024)))
DAEMON_URL = _env("ASIDE_DAEMON_URL", "http://127.0.0.1:21420")

# --- bridge state ------------------------------------------------------
CACHE_DIR = BASE_DIR / "cache"
MEDIA_DIR = CACHE_DIR / "media"
SHOT_DIR = CACHE_DIR / "shots"
for _d in (CACHE_DIR, MEDIA_DIR, SHOT_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# --- tuning ------------------------------------------------------------
# repl sessions die after 30 min idle (replIdleTimeoutMs=1800000). Keep 25 min.
MCP_KEEPALIVE_SEC = int(_env("ASIDE_REMOTE_MCP_KEEPALIVE", "1500"))
MCP_CALL_TIMEOUT = float(_env("ASIDE_REMOTE_MCP_TIMEOUT", "125"))
# Cloudflare Free/Pro drops idle WebSockets after 100 s. Ping every 20 s.
WS_HEARTBEAT_SEC = 20
TAB_CACHE_TTL = 5.0
SHOT_CACHE_TTL = float(_env("ASIDE_REMOTE_SHOT_TTL", "60"))
# how long to watch for the new session directory after spawning `aside exec`
RUN_SESSION_DETECT_SEC = 25.0
JSONL_POLL_SEC = 0.35

# --- notifications (optional) -----------------------------------------
# Push a note (ntfy.sh protocol) when a run finishes. Off unless configured.
NTFY_URL = _env("ASIDE_REMOTE_NTFY", "")
NTFY_TOPIC = _env("ASIDE_REMOTE_NTFY_TOPIC", "aside-runs")
NTFY_ENABLED = bool(NTFY_URL) and _env("ASIDE_REMOTE_NTFY_ENABLED", "1") == "1"

# --- Cloudflare Access bootstrap (optional) ---------------------------
# When the bridge sits behind Cloudflare Access, a browser that passed the
# Access login can fetch the bearer token automatically: the bridge verifies
# the CF Access JWT signature and identity, then hands the token over.
# All three settings empty = feature off; loopback requests still get the
# token (so localhost use needs no setup at all).
ACCESS_TEAM_DOMAIN = _env("ASIDE_REMOTE_ACCESS_TEAM", "")        # e.g. yourteam.cloudflareaccess.com
ACCESS_AUD = _env("ASIDE_REMOTE_ACCESS_AUD", "")                 # Access application AUD tag
ACCESS_EMAILS = {
    e.strip().lower()
    for e in _env("ASIDE_REMOTE_ACCESS_EMAILS", "").split(",")
    if e.strip()
}

# Native apps cannot do the browser login (Google blocks OAuth in WebViews).
# They pass Access with a *service token* instead, whose JWT carries a
# common_name claim rather than email. Allow only our token's common_name —
# signature verification and identity check both stay intact.
def _service_cns() -> set[str]:
    out = set()
    f = Path(_env("ASIDE_REMOTE_CF_SERVICE_TOKEN_FILE",
                  str(HOME / ".aside-remote/cf_service_token.json"))).expanduser()
    try:
        import json as _json
        cid = _json.loads(f.read_text()).get("client_id", "")
        if cid:
            # the client_id itself already ends in ".access" (measured)
            out.add(cid if cid.endswith(".access") else f"{cid}.access")
    except Exception:
        pass
    for extra in _env("ASIDE_REMOTE_ACCESS_CNS", "").split(","):
        if extra.strip():
            out.add(extra.strip())
    return out


ACCESS_SERVICE_CNS = _service_cns()
